name: swipeable_page_route
description: Swipe to navigate back and admire beautifully morphing widgets
version: 0.4.7
repository: https://github.com/JonasWanke/swipeable_page_route

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter